<?php $__env->startSection('title', $campaign->exists ? 'Edit Reward Campaign' : 'Create Reward Campaign'); ?>
<?php $__env->startSection('breadcrumb', 'Admin · Rewards · Campaigns'); ?>
<?php $__env->startSection('content'); ?>
<div class="space-y-4">
    <h1 class="text-lg font-semibold text-gray-900 dark:text-gray-50"><?php echo e($campaign->exists ? 'Edit' : 'Create'); ?> Reward Campaign</h1>
    <?php echo $__env->make('admin.rewards._nav', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?>
    <?php if($errors->any()): ?><div class="rounded border border-red-200 bg-red-50 px-3 py-2 text-xs text-red-700"><?php echo e($errors->first()); ?></div><?php endif; ?>
    <form method="POST" action="<?php echo e($campaign->exists ? route('admin.rewards.campaigns.update', $campaign) : route('admin.rewards.campaigns.store')); ?>" class="space-y-4 rounded-lg border border-gray-200 bg-white p-4 text-xs dark:border-gray-800 dark:bg-gray-950">
        <?php echo csrf_field(); ?>
        <?php if($campaign->exists): ?> <?php echo method_field('PUT'); ?> <?php endif; ?>
        <div class="grid gap-3 md:grid-cols-2">
            <div><label class="block text-[10px] text-gray-500">Name</label><input name="name" value="<?php echo e(old('name', $campaign->name)); ?>" class="w-full rounded border px-2 py-1.5 dark:border-gray-700 dark:bg-gray-950"></div>
            <div><label class="block text-[10px] text-gray-500">Status</label><select name="status" class="w-full rounded border px-2 py-1.5 dark:border-gray-700 dark:bg-gray-950"><?php $__currentLoopData = ['draft','active','paused','expired']; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $s): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($s); ?>" <?php if(old('status', $campaign->status ?: 'draft')===$s): echo 'selected'; endif; ?>><?php echo e(str($s)->headline()); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></div>
            <div><label class="block text-[10px] text-gray-500">Type</label><select name="type" class="w-full rounded border px-2 py-1.5 dark:border-gray-700 dark:bg-gray-950"><?php $__currentLoopData = ['order','product','category','fixed_bonus']; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $t): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($t); ?>" <?php if(old('type', $campaign->type ?: 'order')===$t): echo 'selected'; endif; ?>><?php echo e(str($t)->headline()); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></div>
            <div><label class="block text-[10px] text-gray-500">Eligible tiers</label><select multiple name="eligible_tiers[]" class="w-full rounded border px-2 py-1.5 dark:border-gray-700 dark:bg-gray-950"><?php ($selectedTiers=old('eligible_tiers', $campaign->eligible_tiers ?? [])); ?><?php $__currentLoopData = $tiers; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $tier): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($tier->key); ?>" <?php if(in_array($tier->key, $selectedTiers, true)): echo 'selected'; endif; ?>><?php echo e($tier->name); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select><div class="mt-1 text-[10px] text-gray-500">Leave blank for all tiers.</div></div>
            <div><label class="block text-[10px] text-gray-500">Starts at</label><input type="datetime-local" name="starts_at" value="<?php echo e(old('starts_at', optional($campaign->starts_at)->format('Y-m-d\TH:i'))); ?>" class="w-full rounded border px-2 py-1.5 dark:border-gray-700 dark:bg-gray-950"></div>
            <div><label class="block text-[10px] text-gray-500">Ends at</label><input type="datetime-local" name="ends_at" value="<?php echo e(old('ends_at', optional($campaign->ends_at)->format('Y-m-d\TH:i'))); ?>" class="w-full rounded border px-2 py-1.5 dark:border-gray-700 dark:bg-gray-950"></div>
            <div><label class="block text-[10px] text-gray-500">Minimum order amount</label><input type="number" step="0.01" name="min_order_amount" value="<?php echo e(old('min_order_amount', $campaign->min_order_amount)); ?>" class="w-full rounded border px-2 py-1.5 dark:border-gray-700 dark:bg-gray-950"></div>
            <div><label class="block text-[10px] text-gray-500">Multiplier</label><input type="number" step="0.001" min="1" name="multiplier" value="<?php echo e(old('multiplier', $campaign->multiplier ?: 1)); ?>" class="w-full rounded border px-2 py-1.5 dark:border-gray-700 dark:bg-gray-950"><div class="mt-1 text-[10px] text-gray-500">2 means double normal tier earning.</div></div>
            <div><label class="block text-[10px] text-gray-500">Fixed bonus points</label><input type="number" name="fixed_bonus_points" value="<?php echo e(old('fixed_bonus_points', $campaign->fixed_bonus_points)); ?>" class="w-full rounded border px-2 py-1.5 dark:border-gray-700 dark:bg-gray-950"></div>
            <div><label class="block text-[10px] text-gray-500">Max bonus/order</label><input type="number" name="max_bonus_per_order" value="<?php echo e(old('max_bonus_per_order', $campaign->max_bonus_per_order)); ?>" class="w-full rounded border px-2 py-1.5 dark:border-gray-700 dark:bg-gray-950"></div>
            <div><label class="block text-[10px] text-gray-500">Max bonus/customer</label><input type="number" name="max_bonus_per_customer" value="<?php echo e(old('max_bonus_per_customer', $campaign->max_bonus_per_customer)); ?>" class="w-full rounded border px-2 py-1.5 dark:border-gray-700 dark:bg-gray-950"></div>
            <div><label class="block text-[10px] text-gray-500">Budget points</label><input type="number" name="budget_points" value="<?php echo e(old('budget_points', $campaign->budget_points)); ?>" class="w-full rounded border px-2 py-1.5 dark:border-gray-700 dark:bg-gray-950"></div>
        </div>
        <div><label class="block text-[10px] text-gray-500">Description</label><textarea name="description" rows="3" class="w-full rounded border px-2 py-1.5 dark:border-gray-700 dark:bg-gray-950"><?php echo e(old('description', $campaign->description)); ?></textarea></div>
        <label class="inline-flex items-center gap-2"><input type="checkbox" name="counts_toward_tier" value="1" <?php if(old('counts_toward_tier', $campaign->counts_toward_tier)): echo 'checked'; endif; ?>><span>Promo bonus counts toward tier progress</span></label>
        <div class="grid gap-3 md:grid-cols-2">
            <div><label class="block text-[10px] text-gray-500">Product scope</label><select multiple name="product_ids[]" class="h-44 w-full rounded border px-2 py-1.5 dark:border-gray-700 dark:bg-gray-950"><?php ($selectedProducts=old('product_ids', $campaign->exists ? $campaign->products()->pluck('products.id')->all() : [])); ?><?php $__currentLoopData = $products; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $product): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($product->id); ?>" <?php if(in_array($product->id, $selectedProducts)): echo 'selected'; endif; ?>><?php echo e($product->name); ?> <?php if($product->sku): ?> · <?php echo e($product->sku); ?> <?php endif; ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></div>
            <div><label class="block text-[10px] text-gray-500">Category scope</label><select multiple name="category_ids[]" class="h-44 w-full rounded border px-2 py-1.5 dark:border-gray-700 dark:bg-gray-950"><?php ($selectedCategories=old('category_ids', $campaign->exists ? $campaign->categories()->pluck('categories.id')->all() : [])); ?><?php $__currentLoopData = $categories; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $category): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($category->id); ?>" <?php if(in_array($category->id, $selectedCategories)): echo 'selected'; endif; ?>><?php echo e($category->name); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></div>
        </div>
        <div class="flex gap-2"><button class="rounded bg-gray-900 px-3 py-1.5 text-white dark:bg-gray-100 dark:text-gray-900">Save campaign</button><a href="<?php echo e(route('admin.rewards.campaigns.index')); ?>" class="rounded border px-3 py-1.5 dark:border-gray-700">Cancel</a></div>
    </form>
</div>
<?php $__env->stopSection(); ?>

<?php echo $__env->make('layouts.company', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php /**PATH /Users/ooglie/Website/ChatGPT/PRODUCTIONFrozen/BandaraFrozen/resources/views/admin/rewards/campaigns/form.blade.php ENDPATH**/ ?>