<?php $__env->startSection('title', 'Reward Customers'); ?>
<?php $__env->startSection('breadcrumb', 'Admin · Rewards · Customers'); ?>
<?php $__env->startSection('content'); ?>
<div class="space-y-4">
    <h1 class="text-lg font-semibold text-gray-900 dark:text-gray-50">B2C Reward Customers</h1>
    <?php echo $__env->make('admin.rewards._nav', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?>
    <?php if(session('status')): ?><div class="rounded border border-emerald-200 bg-emerald-50 px-3 py-2 text-xs text-emerald-700"><?php echo e(session('status')); ?></div><?php endif; ?>
    <?php if($errors->any()): ?><div class="rounded border border-red-200 bg-red-50 px-3 py-2 text-xs text-red-700"><?php echo e($errors->first()); ?></div><?php endif; ?>
    <div class="grid gap-4 xl:grid-cols-3">
        <div class="rounded-lg border border-gray-200 bg-white dark:border-gray-800 dark:bg-gray-950 xl:col-span-2 overflow-x-auto"><table class="min-w-full text-xs"><thead class="text-left text-gray-500"><tr><th class="p-3">Customer</th><th class="p-3">Tier</th><th class="p-3">Balance</th><th class="p-3">Type</th></tr></thead><tbody><?php $__currentLoopData = $customers; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $customer): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><tr class="border-t border-gray-100 dark:border-gray-800"><td class="p-3"><div class="font-medium text-gray-900 dark:text-gray-50"><?php echo e($customer->name); ?></div><div class="text-gray-500"><?php echo e($customer->email); ?> · #<?php echo e($customer->id); ?></div></td><td class="p-3"><?php echo e(str($customer->reward_tier ?? 'silver')->title()); ?></td><td class="p-3"><?php echo e(number_format($customer->reward_balance ?? 0)); ?></td><td class="p-3"><?php echo e(strtoupper($customer->customer_type ?? 'b2c')); ?></td></tr><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></tbody></table></div>
        <form method="POST" action="<?php echo e(route('admin.rewards.adjustments.store')); ?>" class="rounded-lg border border-gray-200 bg-white p-4 text-xs dark:border-gray-800 dark:bg-gray-950"><?php echo csrf_field(); ?><h2 class="text-sm font-semibold text-gray-900 dark:text-gray-50">Manual adjustment</h2><p class="mt-1 text-gray-500">Only B2C users are accepted. Use negative amount for debit.</p><div class="mt-3 space-y-2"><input name="user_id" placeholder="User ID" class="w-full rounded border px-2 py-1 dark:border-gray-700 dark:bg-gray-950"><input type="number" name="amount" placeholder="Wallet points + / -" class="w-full rounded border px-2 py-1 dark:border-gray-700 dark:bg-gray-950"><input type="number" name="tier_points" placeholder="Tier points effect (optional)" class="w-full rounded border px-2 py-1 dark:border-gray-700 dark:bg-gray-950"><textarea name="note" rows="3" placeholder="Reason" class="w-full rounded border px-2 py-1 dark:border-gray-700 dark:bg-gray-950"></textarea><button class="rounded bg-gray-900 px-3 py-1.5 text-white dark:bg-gray-100 dark:text-gray-900">Post adjustment</button></div></form>
    </div>
    <?php echo e($customers->links()); ?>

</div>
<?php $__env->stopSection(); ?>

<?php echo $__env->make('layouts.company', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php /**PATH /Users/ooglie/Website/ChatGPT/PRODUCTIONFrozen/BandaraFrozen/resources/views/admin/rewards/customers.blade.php ENDPATH**/ ?>